- name: Install and configure Prometheus
  hosts: master1
  become: true
  vars_files:
  - vars/sudo_password.yml
  roles:
  - prometheus
  - grafana

- name: Install and configure node-exporter
  hosts: worker1
  become: true
  vars_files:
  - vars/sudo_password.yml
  roles:
  - node-exporter
