# tasks file for grafana
- name: Add Grafana GPG key to keyring
  shell: "{{ grafana_gpg_key }}"
  ignore_errors: true
  changed_when: false

- name: Add Grafana repository to sources.list
  shell: "{{ grafana_repo }}"

- name: Update APT cache
  apt:
    update_cache: yes

- name: Install Grafana
  apt:
    name: grafana
    state: present
  notify:
  - Start Grafana Service

- name: Enable the Grafana service
  systemd:
    name: grafana-server
    enabled: yes
  become: true

- name: "UFW - Allow 3000 port"
  ufw:
    rule: allow
    port: 3000
    proto: tcp
