# vars file for prometheus
username: "prometheus"
#prometheus_url: "https://github.com/prometheus/prometheus/releases/download/v2.47.1/prometheus-2.47.1.linux-amd64.tar.gz"
prometheus_version: "2.47.1"
